package com.euler;

/**
 *  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 *
 */
public class Problem002 {
    public static void main(String[] args) {

        int max = 4000000;
        System.out.println(String.format("The sum of the even Fibonacci numbers under %d is: %d", max, getEvenFibSum(max)));

    }

    public static int getEvenFibSum (int n){
        int sum = 2;    //first fib number is even
        int a = 1, b = 2;  //first two fib numbers
        int c;

        while (sum < n){
            System.out.println(a);
            c = b;
            b = b + a;
            a = c;
            if (b % 2 == 0){
                sum += b;
            }
        }
        return sum;
    }

}
